version: 2.1

parameters:
  deploy-service-a:
    type: boolean
    default: false
  deploy-service-b:
    type: boolean
    default: false
  deploy-service-c:
    type: boolean
    default: false
  deploy-all:
    type: boolean
    default: false

jobs:
  echo:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: echo
          command: 'echo "Running echo job"'
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: build
          command: 'echo "Running build job"'
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: build
          command: 'echo "Running build job"'
workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
  service-a:
    when:
      and:
        - or: [<< pipeline.parameters.deploy-service-a >>, << pipeline.parameters.deploy-all >>]
        - equal: [main, << pipeline.git.branch >>]
    jobs:
      - echo
  service-b:
    when:
      and:
        - or: [<< pipeline.parameters.deploy-service-a >>, << pipeline.parameters.deploy-all >>]
        - equal: [main, << pipeline.git.branch >>]
    jobs:
      - echo
  service-c:
    when:
      and:
        - or: [<< pipeline.parameters.deploy-service-a >>, << pipeline.parameters.deploy-all >>]
        - equal: [main, << pipeline.git.branch >>]
    jobs:
      - echo
