version: 2.1

parameters:
  deploy-service-a:
    type: boolean
    default: false
  deploy-service-b:
    type: boolean
    default: false
  deploy-service-c:
    type: boolean
    default: false
  deploy-all:
    type: boolean
    default: false

jobs:
  echo:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: echo
          command: 'echo "Running echo job"'

workflows:
  service-a:
    # deploy when service-a or all
    when: << pipeline.parameters.deploy-service-a >> || << pipeline.parameters.deploy-all >>
    jobs:
      - echo
  service-b:
    when: << pipeline.parameters.deploy-service-b >> || << pipeline.parameters.deploy-all >>
    jobs:
      - echo
  service-c:
    when: << pipeline.parameters.deploy-service-c >> || << pipeline.parameters.deploy-all >>
    jobs:
      - echo
